- name: Adding generic input rules
  routeros_command:
      commands:
        - /routing filter add chain=self-net-in prefix=45.90.160.0/24 invert-match=no action=discard set-bgp-prepend-path=""
        - /routing filter add chain=self-net-in prefix=2a0d:ef00::/48 invert-match=no action=discard set-bgp-prepend-path=""
        - /routing filter add chain=self-net-in invert-match=no action=jump jump-target=GENERIC_PREFIX_LIST set-bgp-prepend-path=""

- name: Adding generic output rules
  routeros_command:
      commands:
        - /routing filter add chain=self-net-out prefix=45.90.160.0/24 invert-match=no action=accept set-bgp-prepend-path=""
        - /routing filter add chain=self-net-out prefix=2a0d:ef00::/48 invert-match=no action=accept set-bgp-prepend-path=""

- name: Adding generic Fullview output rules
  routeros_command:
        commands:
          - /routing filter add chain=self-net-full-out prefix=45.90.160.0/24 prefix-length=25-32 invert-match=no action=discard set-bgp-prepend-path=""
          - /routing filter add chain=self-net-full-out prefix=2a0d:ef00::/48 prefix-length=49-128 invert-match=no action=discard set-bgp-prepend-path=""
          - /routing filter add chain=self-net-full-out invert-match=no action=jump jump-target=GENERIC_PREFIX_LIST set-bgp-prepend-path=""
