- name: Adding Specific Rules
  routeros_command:
      commands:
        - /routing filter add chain=Adista-in invert-match=no action=jump jump-target=self-net-in set-bgp-prepend-path=""
        - /routing filter add chain=Adista-in invert-match=no action=accept set-bgp-local-pref=300 set-bgp-prepend-path=""
        - /routing filter add chain=Adista-out invert-match=no action=jump jump-target=self-net-out set-bgp-prepend-path=""
        - /routing filter add chain=Adista-out invert-match=no action=discard set-bgp-prepend-path=""
        - /routing filter add chain=Lillix-in invert-match=no action=jump jump-target=self-net-in set-bgp-prepend-path=""
        - /routing filter add chain=Lillix-in invert-match=no action=accept set-bgp-local-pref=300 set-bgp-prepend-path=""
        - /routing filter add chain=Lillix-out invert-match=no action=jump jump-target=self-net-out set-bgp-prepend-path=""
        - /routing filter add chain=Lillix-out invert-match=no action=discard set-bgp-prepend-path=""
        - /routing filter add chain=OVH-in invert-match=no action=jump jump-target=self-net-in set-bgp-prepend-path=""
        - /routing filter add chain=OVH-in invert-match=no action=accept set-bgp-local-pref=300 set-bgp-prepend-path=""
        - /routing filter add chain=OVH-out invert-match=no action=jump jump-target=self-net-out set-bgp-prepend-path=""
        - /routing filter add chain=OVH-out invert-match=no action=discard set-bgp-prepend-path=""
        - /routing filter add chain=Dorian-Galiana-in invert-match=no action=jump jump-target=self-net-in set-bgp-prepend-path=""
        - /routing filter add chain=Dorian-Galiana-in invert-match=no action=accept set-bgp-local-pref=200 set-bgp-prepend-path=""
        - /routing filter add chain=Dorian-Galiana-out invert-match=no action=jump jump-target=self-net-out set-bgp-prepend-path=""
        - /routing filter add chain=Dorian-Galiana-out invert-match=no action=discard set-bgp-prepend-path=""
        - /routing filter add chain=Milkywan-in invert-match=no action=jump jump-target=self-net-in set-bgp-prepend-path=""
        - /routing filter add chain=Milkywan-in invert-match=no action=accept set-bgp-local-pref=200 set-bgp-prepend-path=""
        - /routing filter add chain=Milkywan-out invert-match=no action=jump jump-target=self-net-out set-bgp-prepend-path=""
        - /routing filter add chain=Milkywan-out invert-match=no action=discard set-bgp-prepend-path=""
